CREATE TABLE `creaturecache` (
  `entry` mediumint(8) unsigned NOT NULL default '0',
  `name` varchar(255) NOT NULL,
  `subname` varchar(255) NOT NULL,
  `iconname` varchar(255) NOT NULL,
  `TypeFlags` int(10) unsigned NOT NULL default '0',
  `Type` int(10) unsigned NOT NULL default '0',
  `Family` int(10) unsigned NOT NULL default '0',
  `Rank` int(10) unsigned NOT NULL default '0',
  `KillCredid1` int(10) unsigned NOT NULL default '0',
  `KillCredid2` int(10) unsigned NOT NULL default '0',
  `Model1` int(10) unsigned NOT NULL default '0',
  `Model2` int(10) unsigned NOT NULL default '0',
  `Model3` int(10) unsigned NOT NULL default '0',
  `Model4` int(10) unsigned NOT NULL default '0',
  `Unk1` float NOT NULL default '0',
  `Unk2` float NOT NULL default '0',
  `RacialLeader` int(10) unsigned NOT NULL default '0',
  `Item1` int(10) unsigned NOT NULL default '0',
  `Item2` int(10) unsigned NOT NULL default '0',
  `Item3` int(10) unsigned NOT NULL default '0',
  `Item4` int(10) unsigned NOT NULL default '0',
  `Item5` int(10) unsigned NOT NULL default '0',
  `Item6` int(10) unsigned NOT NULL default '0',
  `MovementId` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`entry`),
  KEY `idx_name` (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
