CREATE TABLE `questcache` (
  `Entry` mediumint(8) unsigned NOT NULL default '0',
  `Method` mediumint(8) unsigned NOT NULL default '0',
  `QuestLevel` mediumint(8) NOT NULL default '0',
  `MinLevel` mediumint(8) unsigned NOT NULL default '0',
  `ZoneOrSort` mediumint(8) NOT NULL default '0',
  `Type` mediumint(8) unsigned NOT NULL default '0',
  `SuggestedPlayers` mediumint(8) unsigned NOT NULL default '0',
  `RepObjFaction` mediumint(8) unsigned NOT NULL default '0',
  `RepObjValue` mediumint(8) NOT NULL default '0',
  `RepObjFaction1` mediumint(8) unsigned NOT NULL default '0',
  `RepObjValue1` mediumint(8) NOT NULL default '0',
  `NextQuest` mediumint(8) unsigned NOT NULL default '0',
  `Unk1` mediumint(8) unsigned NOT NULL default '0',
  `RewOrReqMoney` mediumint(8) NOT NULL default '0',
  `RewMoneyMaxLevel` mediumint(8) unsigned NOT NULL default '0',
  `RewSpell` mediumint(8) unsigned NOT NULL default '0',
  `RewSpellCast` mediumint(8) unsigned NOT NULL default '0',
  `Honor1` mediumint(8) unsigned NOT NULL default '0',
  `Honor2` float NOT NULL default '0',
  `SrcItemId` mediumint(8) unsigned NOT NULL default '0',
  `QuestFlags` mediumint(8) unsigned NOT NULL default '0',
  `RewTitle` mediumint(8) unsigned NOT NULL default '0',
  `ReqPlayersSlain` mediumint(8) unsigned NOT NULL default '0',
  `BonusTalents` mediumint(8) unsigned NOT NULL default '0',
  `BonusArenaPoints` mediumint(8) unsigned NOT NULL default '0',
  `Unk2` mediumint(8) unsigned NOT NULL default '0',
  `RewItemId1` mediumint(8) unsigned NOT NULL default '0',
  `RewItemCount1` mediumint(8) unsigned NOT NULL default '0',
  `RewItemId2` mediumint(8) unsigned NOT NULL default '0',
  `RewItemCount2` mediumint(8) unsigned NOT NULL default '0',
  `RewItemId3` mediumint(8) unsigned NOT NULL default '0',
  `RewItemCount3` mediumint(8) unsigned NOT NULL default '0',
  `RewItemId4` mediumint(8) unsigned NOT NULL default '0',
  `RewItemCount4` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemId1` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemCount1` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemId2` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemCount2` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemId3` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemCount3` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemId4` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemCount4` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemId5` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemCount5` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemId6` mediumint(8) unsigned NOT NULL default '0',
  `RewChoiseItemCount6` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionId1` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionId2` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionId3` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionId4` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionId5` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionVal1` mediumint(8) NOT NULL default '0',
  `RewFactionVal2` mediumint(8) NOT NULL default '0',
  `RewFactionVal3` mediumint(8) NOT NULL default '0',
  `RewFactionVal4` mediumint(8) NOT NULL default '0',
  `RewFactionVal5` mediumint(8) NOT NULL default '0',
  `RewFactionValOverride1` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionValOverride2` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionValOverride3` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionValOverride4` mediumint(8) unsigned NOT NULL default '0',
  `RewFactionValOverride5` mediumint(8) unsigned NOT NULL default '0',
  `MapId` mediumint(8) unsigned NOT NULL default '0',
  `X` float NOT NULL default '0',
  `Y` float NOT NULL default '0',
  `Unk3` mediumint(8) unsigned NOT NULL default '0',
  `Title` varchar(255) NOT NULL,
  `Objectives` varchar(255) NOT NULL,
  `Details` varchar(255) NOT NULL,
  `ToDoText` varchar(255) NOT NULL,
  `EndText` varchar(255) NOT NULL,
  `ReqCreatureOrGoId1` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoCount1` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceId1` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceIdMaxCount1` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoId2` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoCount2` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceId2` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceIdMaxCount2` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoId3` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoCount3` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceId3` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceIdMaxCount3` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoId4` mediumint(8) unsigned NOT NULL default '0',
  `ReqCreatureOrGoCount4` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceId4` mediumint(8) unsigned NOT NULL default '0',
  `ReqSourceIdMaxCount4` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemId1` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount1` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemId2` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount2` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemId3` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount3` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemId4` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount4` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemId5` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount5` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemId6` mediumint(8) unsigned NOT NULL default '0',
  `ReqItemCount6` mediumint(8) unsigned NOT NULL default '0',
  `ObjectiveText1` varchar(255) NOT NULL,
  `ObjectiveText2` varchar(255) NOT NULL,
  `ObjectiveText3` varchar(255) NOT NULL,
  `ObjectiveText4` varchar(255) NOT NULL,
  PRIMARY KEY  (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
